# 1. np.c_

np.c_是 NumPy 提供的一种简写符号，用于通过沿第二个轴堆叠数字来创建数组，通常用于连接两个或多个数组或从现有数组创建新数组。

(1) 连接数组：您可以用来np.c_沿第二个轴（列）连接两个或多个数组，有效地水平堆叠它们。当使用一维数组创建二维数组时，这特别有用。例如：

In [1]:
import numpy as np

array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

concatenated = np.c_[array1, array2]

print(concatenated)


[[1 4]
 [2 5]
 [3 6]]


（2）创建新数组：您还可以使用np.c_现有数组创建新数组，在每列中定义所需的值。例如：

In [3]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

new_array = np.c_[array1, 10 * array2, array1**2]

print(new_array)

[[ 1 40  1]
 [ 2 50  4]
 [ 3 60  9]]


np.c_是使用 NumPy 数组的便捷方法，特别是当您想要连接数组或按列构建新数组时。沿第一轴（行）串联的对应项是np.r_。